### ISSUE TITLE
Fails to build on Python 3.13

### ISSUE THREAD

**Issue by samcday** [bkerler/edl#615]
```
src/pylzma/pylzma.c: In function ‘PyInit_pylzma’:
src/pylzma/pylzma.c:296:5: warning: ‘PyEval_InitThreads’ is deprecated [-Wdeprecated-declarations]
  296 |     PyEval_InitThreads();
      |     ^~~~~~~~~~~~~~~~~~
In file included from /usr/include/python3.13/Python.h:124,
                 from src/pylzma/pylzma.c:26:
/usr/include/python3.13/ceval.h:114:37: note: declared here
  114 | Py_DEPRECATED(3.9) PyAPI_FUNC(void) PyEval_InitThreads(void);
      |                                     ^~~~~~~~~~~~~~~~~~
src/pylzma/pylzma_aes.c:158:5: error: initialization of ‘long int’ from ‘void *’ makes integer from pointer without a cast [-Wint-conversion]
  158 |     NULL,                                /* printfunc  tp_print;   */
      |     ^~~~
src/pylzma/pylzma_aes.c:158:5: note: (near initialization for ‘CAESDecrypt_Type.tp_vectorcall_offset’)
error: Setup script exited with error: command '/usr/bin/gcc' failed with exit code 1
```

I encountered this on Fedora 41 which ships Python 3.13. [It seems @abdedarghal111 also ran into this on Arch](https://github.com/bkerler/edl/issues/245#issuecomment-2428960669)

**Comment by samcday** [comment]
Seems like pylzma is quite inactive. A kind soul on that project's issue tracker [suggested a fix](https://github.com/fancycode/pylzma/issues/80) which worked for me:

```
sudo CFLAGS=-Wno-int-conversion python3 setup.py install
```

**Comment by rcky844** [comment]
I just tried it on Python 3.13, and it seems broken with that.

**Comment by samcday** [comment]
Did you try the workaround I posted in the previous comment? I successfully built and used edl from source last week with Python 3.13.1 (Fedora 41 distro package).

**Comment by rcky844** [comment]
> Did you try the workaround I posted in the previous comment? I successfully built and used edl from source last week with Python 3.13.1 (Fedora 41 distro package) with that One Weird Trick 🤷

I found out that my board's EMMC died, and it seems unrelated to edl.
And no, I did not need your workaround to build at all.

**Comment by RenateUSB** [comment]
If the eMMC actually failed you should be able to ascertain that by using EDL. Just run it verbose and get the 532 extended CSD bytes.

**Comment by rcky844** [comment]
> If the eMMC actually failed you should be able to ascertain that by using EDL. Just run it verbose and get the 532 extended CSD bytes.

Can't really confirm any of that now, I probably shorted out the whole board or something right after the comment.

**Comment by HasanEsa** [comment]
> Seems like pylzma is quite inactive. A kind soul on that project's issue tracker [suggested a fix](https://github.com/fancycode/pylzma/issues/80#issuecomment-2371096041) which worked for me:
> 
> ```
> sudo CFLAGS=-Wno-int-conversion python3 setup.py install
> ```

I can confirm that this flag solves the issue. I'm on Fedora 42 and latest master branch. This issue may be closed.

**Comment by samcday** [comment]
> This issue may be closed.

I'd prefer this issue remain open until this project has either switched to a new dependency or patched its build with the workaround.
